package b4a.OrderTakerTest1.designerscripts;
import anywheresoftware.b4a.objects.TextViewWrapper;
import anywheresoftware.b4a.objects.ImageViewWrapper;
import anywheresoftware.b4a.BA;


public class LS_userorders{

public static void LS_general(anywheresoftware.b4a.BA ba, android.view.View parent, anywheresoftware.b4a.keywords.LayoutValues lv, java.util.Map props,
java.util.Map<String, anywheresoftware.b4a.keywords.LayoutBuilder.ViewWrapperAndAnchor> views, int width, int height, float scale) throws Exception {
anywheresoftware.b4a.keywords.LayoutBuilder.setScaleRate(0.3);
anywheresoftware.b4a.keywords.LayoutBuilder.scaleAll(views);
views.get("pnldim").vw.setWidth((int)((100d / 100 * width)));
views.get("pnldim").vw.setHeight((int)((100d / 100 * height)));
views.get("pnldim").vw.setLeft((int)((0d * scale)));
views.get("pnldim").vw.setTop((int)((0d * scale)));
views.get("panel1").vw.setTop((int)(0d));
views.get("panel1").vw.setLeft((int)(0d));
views.get("panel1").vw.setWidth((int)((100d / 100 * width)));
views.get("panel1").vw.setHeight((int)((70d * scale)));
views.get("bttnaddorder").vw.setLeft((int)((40d / 100 * width)));
views.get("bttnaddorder").vw.setWidth((int)((20d / 100 * width)));
views.get("bttnaddorder").vw.setTop((int)((75d / 100 * height)));
views.get("pnladdorderhometotal").vw.setLeft((int)((5d * scale)));
views.get("pnladdorderhometotal").vw.setWidth((int)((96.5d / 100 * width)));
views.get("pnladdorderhometotal").vw.setTop((int)((75d * scale)));
views.get("pnladdorderhometotal").vw.setHeight((int)((350d * scale)));
views.get("btnadditems").vw.setLeft((int)((10d * scale)));
views.get("btnadditems").vw.setWidth((int)((100d / 100 * width)-(30d * scale)));
views.get("btnadditems").vw.setTop((int)((252d * scale)));
views.get("btnpurchasenow").vw.setLeft((int)((10d * scale)));
views.get("btnpurchasenow").vw.setWidth((int)((100d / 100 * width)-(30d * scale)));
views.get("btnpurchasenow").vw.setTop((int)((300d * scale)));
views.get("lblexitaddorderhome").vw.setLeft((int)((262d * scale)));
views.get("lblexitaddorderhome").vw.setTop((int)((5d * scale)));
((anywheresoftware.b4a.keywords.LayoutBuilder.DesignerTextSizeMethod)views.get("lblexitaddorderhome").vw).setTextSize((float)(20d));
views.get("lblperson").vw.setLeft((int)((10d * scale)));
views.get("lblperson").vw.setWidth((int)((30d * scale)));
views.get("lblperson").vw.setHeight((int)((30d * scale)));
views.get("lblperson").vw.setTop((int)(((views.get("panel1").vw.getHeight())-(views.get("lblperson").vw.getHeight()))/2d));
views.get("lblloggedinuser").vw.setLeft((int)((views.get("lblperson").vw.getLeft() + views.get("lblperson").vw.getWidth())+(8d * scale)));
views.get("lblloggedinuser").vw.setWidth((int)((25d / 100 * width)));
views.get("lblloggedinuser").vw.setTop((int)(((views.get("panel1").vw.getHeight())-(views.get("lblloggedinuser").vw.getHeight()))/2d));
views.get("spinner1").vw.setLeft((int)((views.get("lblloggedinuser").vw.getLeft() + views.get("lblloggedinuser").vw.getWidth())+(8d * scale)));
views.get("spinner1").vw.setLeft((int)((80d / 100 * width) - (views.get("spinner1").vw.getWidth())));
views.get("spinner1").vw.setTop((int)(((views.get("panel1").vw.getHeight())-(views.get("spinner1").vw.getHeight()))/2d));
views.get("lbllogout").vw.setWidth((int)((50d * scale)));
views.get("lbllogout").vw.setTop((int)(((views.get("panel1").vw.getHeight())-(views.get("lbllogout").vw.getHeight()))/2d));
views.get("lbllogout").vw.setLeft((int)((100d / 100 * width)-(views.get("lbllogout").vw.getWidth())-(10d * scale)));
views.get("pnlbottomnav").vw.setHeight((int)((60d * scale)));
views.get("pnlbottomnav").vw.setLeft((int)(0d));
views.get("pnlbottomnav").vw.setWidth((int)((100d / 100 * width)));
views.get("pnlbottomnav").vw.setTop((int)((100d / 100 * height)-(views.get("pnlbottomnav").vw.getHeight())));
views.get("pnldash").vw.setLeft((int)(0d));
views.get("pnldash").vw.setWidth((int)((views.get("pnlbottomnav").vw.getWidth())/4d));
views.get("pnldash").vw.setHeight((int)((views.get("pnlbottomnav").vw.getHeight())));
views.get("pnldash").vw.setTop((int)(0d));
((anywheresoftware.b4a.keywords.LayoutBuilder.DesignerTextSizeMethod)views.get("lbldashicon").vw).setTextSize((float)(22d));
views.get("lbldashicon").vw.setWidth((int)((views.get("pnldash").vw.getWidth())));
views.get("lbldashicon").vw.setLeft((int)(0d));
views.get("lbldashicon").vw.setTop((int)((6d * scale)));
views.get("lbldashicon").vw.setHeight((int)((26d * scale)));
views.get("lbldash").vw.setWidth((int)((views.get("pnldash").vw.getWidth())));
views.get("lbldash").vw.setLeft((int)(0d));
views.get("lbldash").vw.setTop((int)((views.get("lbldashicon").vw.getTop() + views.get("lbldashicon").vw.getHeight())+(2d * scale)));
views.get("lbldash").vw.setHeight((int)((20d * scale)));
views.get("pnlorders").vw.setLeft((int)((views.get("pnlbottomnav").vw.getWidth())/4d));
views.get("pnlorders").vw.setWidth((int)((views.get("pnlbottomnav").vw.getWidth())/4d));
views.get("pnlorders").vw.setHeight((int)((views.get("pnlbottomnav").vw.getHeight())));
views.get("pnlorders").vw.setTop((int)(0d));
((anywheresoftware.b4a.keywords.LayoutBuilder.DesignerTextSizeMethod)views.get("lblordersicon").vw).setTextSize((float)(22d));
views.get("lblordersicon").vw.setWidth((int)((views.get("pnlorders").vw.getWidth())));
views.get("lblordersicon").vw.setLeft((int)(0d));
views.get("lblordersicon").vw.setTop((int)((6d * scale)));
views.get("lblordersicon").vw.setHeight((int)((26d * scale)));
views.get("lblorders").vw.setWidth((int)((views.get("pnlorders").vw.getWidth())));
views.get("lblorders").vw.setLeft((int)(0d));
views.get("lblorders").vw.setTop((int)((views.get("lblordersicon").vw.getTop() + views.get("lblordersicon").vw.getHeight())+(2d * scale)));
views.get("lblorders").vw.setHeight((int)((20d * scale)));
views.get("pnlinventory").vw.setLeft((int)((views.get("pnlbottomnav").vw.getWidth())/2d));
views.get("pnlinventory").vw.setWidth((int)((views.get("pnlbottomnav").vw.getWidth())/4d));
views.get("pnlinventory").vw.setHeight((int)((views.get("pnlbottomnav").vw.getHeight())));
views.get("pnlinventory").vw.setTop((int)(0d));
((anywheresoftware.b4a.keywords.LayoutBuilder.DesignerTextSizeMethod)views.get("lblinventoryicon").vw).setTextSize((float)(22d));
views.get("lblinventoryicon").vw.setWidth((int)((views.get("pnlinventory").vw.getWidth())));
views.get("lblinventoryicon").vw.setLeft((int)(0d));
views.get("lblinventoryicon").vw.setTop((int)((6d * scale)));
views.get("lblinventoryicon").vw.setHeight((int)((26d * scale)));
views.get("lblinventory").vw.setWidth((int)((views.get("pnlinventory").vw.getWidth())));
views.get("lblinventory").vw.setLeft((int)(0d));
views.get("lblinventory").vw.setTop((int)((views.get("lblinventoryicon").vw.getTop() + views.get("lblinventoryicon").vw.getHeight())+(2d * scale)));
views.get("lblinventory").vw.setHeight((int)((20d * scale)));
views.get("pnlhistory").vw.setLeft((int)((views.get("pnlbottomnav").vw.getWidth())*3d/4d));
views.get("pnlhistory").vw.setWidth((int)((views.get("pnlbottomnav").vw.getWidth())/4d));
views.get("pnlhistory").vw.setHeight((int)((views.get("pnlbottomnav").vw.getHeight())));
views.get("pnlhistory").vw.setTop((int)(0d));
((anywheresoftware.b4a.keywords.LayoutBuilder.DesignerTextSizeMethod)views.get("lblhistoryicon").vw).setTextSize((float)(22d));
views.get("lblhistoryicon").vw.setWidth((int)((views.get("pnlhistory").vw.getWidth())));
views.get("lblhistoryicon").vw.setLeft((int)(0d));
views.get("lblhistoryicon").vw.setTop((int)((6d * scale)));
views.get("lblhistoryicon").vw.setHeight((int)((26d * scale)));
views.get("lblhistory").vw.setWidth((int)((views.get("pnlhistory").vw.getWidth())));
views.get("lblhistory").vw.setLeft((int)(0d));
views.get("lblhistory").vw.setTop((int)((views.get("lblhistoryicon").vw.getTop() + views.get("lblhistoryicon").vw.getHeight())+(2d * scale)));
views.get("lblhistory").vw.setHeight((int)((20d * scale)));
views.get("scrollview1").vw.setTop((int)((views.get("panel1").vw.getTop() + views.get("panel1").vw.getHeight())));
views.get("scrollview1").vw.setLeft((int)(0d));
views.get("scrollview1").vw.setWidth((int)((100d / 100 * width)));
views.get("scrollview1").vw.setHeight((int)((views.get("pnlbottomnav").vw.getTop())-(views.get("panel1").vw.getTop() + views.get("panel1").vw.getHeight())));
views.get("pnlselectitems").vw.setWidth((int)((95d / 100 * width)));
views.get("pnlselectitems").vw.setHeight((int)((85d / 100 * height)));
views.get("pnlselectitems").vw.setLeft((int)(((100d / 100 * width)-(views.get("pnlselectitems").vw.getWidth()))/2d));
views.get("pnlselectitems").vw.setTop((int)(((100d / 100 * height)-(views.get("pnlselectitems").vw.getHeight()))/2d));
views.get("etsearchitems").vw.setLeft((int)((10d * scale)));
views.get("etsearchitems").vw.setTop((int)((10d * scale)));
views.get("etsearchitems").vw.setWidth((int)((views.get("pnlselectitems").vw.getWidth())-(20d * scale)));
views.get("etsearchitems").vw.setHeight((int)((45d * scale)));
views.get("svselectitems").vw.setLeft((int)(0d));
views.get("svselectitems").vw.setTop((int)((views.get("etsearchitems").vw.getTop() + views.get("etsearchitems").vw.getHeight())+(10d * scale)));
views.get("svselectitems").vw.setWidth((int)((views.get("pnlselectitems").vw.getWidth())));
views.get("svselectitems").vw.setHeight((int)((views.get("pnlselectitems").vw.getHeight())-(views.get("svselectitems").vw.getTop())-(10d * scale)));

}
}